services:
  apimongodb:
    image: apimongodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "5000:8080"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6.0 # 
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db 
volumes:
    mongodb_data:
      driver: local